version: '3.8'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  say:
    build: ./speak
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_TOPIC=say
      # Required for audio to work
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    volumes:
      # Required for audio to work
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie
  listen:
    build: ./listen
    depends_on:
      - redis
      - say
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_TOPIC=say
      - OPENWEATHER_APPID=15e79497893ad73998faa51a71efe8c1
    volumes:
      # Use hostmachine timezone
      - /etc/timezone:/etc/timezone:ro
    devices:
      - "/dev/snd:/dev/snd"
